import random
import matplotlib.pyplot as plt
import numpy as np

dna_sequence = (
    "ATGCGTACGATCGTACGTTAGCGTAGCTAGCTGATCGTACGTAGCTAGCATCGTAGCTAGCTGATCGTAGCATCGTACGATC"
    "GTACGATCGTAGCTAGCATCGATGCTAGCTAGCGTACGTAGCTAGCATCGTACGATCGTAGCTAGCTAGCGTAGCTAGCATC"
    "GTAGCTGATCGTACGTAGCTAGCTAGCGTACGATCGTAGCTAGCATCGTACGATCGTAGCTAGCTAGCGTACGTAGCTAGCT"
    "AGCATCGTAGCTGATCGTACGTAGCTAGCATCGTACGATCGTAGCTAGCTAGCGTAGCTAGCATCGTAGCTGATCGTACGTA"
    "GCTAGCTAGCGTACGATCGTAGCTAGCATCGTACGATCGTAGCTAGCTAGCGTACGTAGCTAGCTAGCATCGTAGCTGATCG"
    "TACGTAGCTAGCATCGTACGATCGTAGCTAGCTAGCGTAGCTAGCATCGTAGCTGATCGTACGTAGCTAGCTAGCGTACGAT"
    "CGTAGCTAGCATCGTACGATCGTAGCTAGCTAGCGTACGTAGCTAGCTAGCATCGTAGCTGATCGTACGTAGCTAGCATCGT"
    "ACGATCGTAGCTAGCTAGCGTAGCTAGCATCGTAGCTGATCGTACGTAGCTAGCTAGCGTACGATCGTAGCTAGCATCGTAC"
    "GATCGTAGCTAGCTAGCGTACGTAGCTAGCTAGCATCGTAGCTGATCGTACGTAGCTAGCATCGTACGATCGTAGCTAGCTA"
    "GCGTAGCTAGCATCGTAGCTGATCGTACGTAGCTAGCTAGCGTACGATCGTAGCTAGCATCGTACGATCGTAGCTAGCTAGC"
    "GTACGTAGCTAGCTAGCATCGTAGCTGATCGTACGTAGCTAGCATCGTACGATCGTAGCTAGCTAGCGTAGCTAGCATCGTA"
    "GCTGATCGTACGTAGCTAGCTAGCGTACGATCGTAGCTAGCATCGTACGATCGTAGCTAGCTAGCGTACGTAGCTAGCTAGC"
    "ATCGTAGCTGATCGTACGTAGCTAGCATCGTACGATCGTAGCTAGCTAGCGTAGCTAGCATCGTAGCTGATCGTACGTAGCT"
    "AGCTAGCGTACGATCGTAGCTAGCATCGTACGATCGTAGCTAGCTAGCGTACGTAGCTAGCTAGCATCGTAGCTGATCGTAC"
    "GTAGCTAGCATCGTACGATCGTAGCTAGCTAGCGTAGCTAGCATCGTAGCTGATCGTACGTAGCTAGCTAGCGTACGATCGT"
    "AGCTAGCATCGTACGATCGTAGCTAGCTAGCGTACGTAGCTAGCTAGCATCGTAGCTGATCGTACGTAGCTAGCATCGTACG"
    "ATCGTAGCTAGCTAGCGTAGCTAGCATCGTAGCTGATCGTACGTAGCTAGCTAGCGTACGATCGTAGCTAGCATCGTACGAT"
    "CGTAGCTAGCTAGCGTACGTAGCTAGCTAGCATCGTAGCTGATCGTACGTAGCTAGCATCGTACGATCGTAGCTAGCTAGCG"
    "TAGCTAGCATCGTAGCTGATCGTACGTAGCTAGCTAGCGTACGATCGTAGCTAGCATCGTACGATCGTAGCTAGCTAGCGTA"
    "CGTAGCTAGCTAGCATCGTAGCTGATCGTACGTAGCTAGCATCGTACGATCGTAGCTAGCTAGCGTAGCTAGCATCGTAGCT"
)

samples = []

for _ in range(10):
    sample_length = random.randint(100, len(dna_sequence))

    start = random.randint(0, len(dna_sequence) - sample_length)

    sample = dna_sequence[start:start + sample_length]
    samples.append(sample)

for i, s in enumerate(samples):
    print(f"Samples: {i+1} ----------> {len(s)} characters")

import matplotlib.pyplot as plt
import math

ladder_bp = [3000, 2000, 1500, 1000, 700, 500, 300, 200, 100]

def bp_to_y(bp, max_bp, min_bp):
    lo = math.log10(min_bp)
    hi = math.log10(max_bp)
    t = (hi - math.log10(bp)) / (hi - lo + 1e-12)
    return t

def show_gel_plot(bands):
    max_bp = max(bands)
    min_bp = min(bands)
    y_positions = [bp_to_y(bp, max_bp, min_bp) for bp in bands]

    plt.figure("Gel Simulation", figsize=(5, 8))

    plt.xlim(-0.5, 1.0)
    plt.ylim(1.05, -0.05)

    for y in y_positions:
        plt.hlines(y, xmin=0.3, xmax=0.8, linewidth=10)

    for bp, y in zip(bands, y_positions):
        plt.text(-0.45, y, f"{bp} bp", va="center", fontsize=12)

    plt.xticks([])
    plt.yticks([])
    plt.title("Simulated DNA Ladder", pad=20)

    plt.show()

show_gel_plot(ladder_bp)